version: "3.2"
services:
  mpi_head:
    image: dispel4py/docker.openmpi
    command: /bin/bash -c "sudo apt-get update && sudo apt-get install -y dnsutils && /usr/sbin/sshd -D"
    networks:
      - mpi-overlay
    volumes:
      - data:/home/tutorial/works
    ports: 
     - "22"
  
  mpi_node: 
    image: dispel4py/docker.openmpi
    deploy:
      replicas: 10
    volumes:
      - data:/home/tutorial/works
    networks:
        - mpi-overlay
networks:
  mesos-overlay:
    external:
      name: mesos-overlay 
volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.2.15,nolock,soft,rw"
      device: ":/nfs/nfs"
